#!/usr/bin/env python3
"""
Generates organs/eyes/EXPRESSIONS.md from firmware/expressions.py's
REGISTRY — the single source of truth for what's implemented, what
Henry still needs to draw/clarify, and how each expression behaves.
Re-run this after changing REGISTRY so the doc can't drift out of sync.

Usage:
    python organs/eyes/expression_status.py
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "firmware"))

from expressions import REGISTRY  # noqa: E402

STATUS_LABELS = {
    "implemented": "✅ implemented",
    "needs_redraw": "✏️ needs redraw",
    "planned": "🕓 planned, no art yet",
    "not_an_expression": "ℹ️ not an expression",
}


def _bool(value):
    if value is None:
        return "—"
    return "yes" if value else "no"


def main():
    lines = [
        "<!-- Generated by organs/eyes/expression_status.py from firmware/expressions.py's REGISTRY. -->",
        "<!-- Don't hand-edit — change the registry and re-run the script instead. -->",
        "",
        "# Eye expressions status",
        "",
        "| Expression | Status | Trackable | Blinks | Animates | Source | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, spec in REGISTRY.items():
        lines.append(
            f"| `{name}` | {STATUS_LABELS.get(spec.status, spec.status)} | {_bool(spec.trackable)} | "
            f"{_bool(spec.blinks)} | {_bool(spec.animates)} | {spec.source} | {spec.notes} |"
        )

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "EXPRESSIONS.md")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
