#!/usr/bin/env python3
"""
Generates the docs indexes from their source files, so they can't drift
out of sync (same idea as organs/eyes/expression_status.py):

    docs/roadmap/README.md     from docs/roadmap/items/*.md + phases.md
    docs/decisions/README.md   from docs/decisions/D-*.md
    docs/journal/README.md     from docs/journal/*.md

Also validates the front matter: known statuses, unique ids matching the
filename, and every depends_on / decisions reference pointing at something
that exists. tests/docs/test_docs_index.py runs the same checks.

Usage:
    python docs/build_index.py           # regenerate
    python docs/build_index.py --check   # exit 1 if anything is stale or invalid
"""

import os
import re
import sys

import yaml

DOCS = os.path.dirname(os.path.abspath(__file__))
ITEMS_DIR = os.path.join(DOCS, "roadmap", "items")
DECISIONS_DIR = os.path.join(DOCS, "decisions")
JOURNAL_DIR = os.path.join(DOCS, "journal")
PHASES_FILE = os.path.join(DOCS, "roadmap", "phases.md")

STATUSES = ("in-progress", "next", "blocked", "planned", "idea", "done")  # display order
STATUS_ICONS = {
    "done": "✅", "in-progress": "🔨", "next": "⏭️", "blocked": "⛔", "planned": "📋", "idea": "💡",
}
DECISION_STATUSES = ("proposed", "accepted", "superseded")
KINDS = ("code", "physical", "both", "planning")

HEADER = "<!-- Generated by docs/build_index.py — don't hand-edit; change the source files and re-run it. -->\n\n"


def _front_matter(path):
    with open(path) as f:
        text = f.read()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise ValueError(f"{path}: missing front matter")
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        raise ValueError(f"{path}: bad front matter — {e}") from None


def _load(directory, prefix):
    out = []
    if not os.path.isdir(directory):
        return out
    for name in sorted(os.listdir(directory)):
        if name.startswith(prefix) and name.endswith(".md"):
            meta = _front_matter(os.path.join(directory, name))
            meta["_file"] = name
            out.append(meta)
    return out


def load_phases():
    """[(key, name)] in order, from phases.md headings."""
    phases = []
    with open(PHASES_FILE) as f:
        for line in f:
            m = re.match(r"^## Phase (\d+) · (.+?)\s*$", line)
            if m:
                phases.append((int(m.group(1)), m.group(2)))
            elif line.strip() == "## Ongoing":
                phases.append(("ongoing", "Ongoing"))
    return phases


def validate(items, decisions, phases):
    errors = []
    phase_keys = {k for k, _ in phases}
    item_ids = [i.get("id") for i in items]
    decision_ids = [d.get("id") for d in decisions]
    for ids, kind in ((item_ids, "item"), (decision_ids, "decision")):
        dupes = {i for i in ids if ids.count(i) > 1}
        if dupes:
            errors.append(f"duplicate {kind} ids: {sorted(dupes)}")

    for i in items:
        where = i["_file"]
        if not where.startswith(f"{i.get('id')}-"):
            errors.append(f"{where}: id {i.get('id')!r} doesn't match the filename")
        for field in ("id", "title", "phase", "status", "area", "kind", "updated"):
            if i.get(field) in (None, ""):
                errors.append(f"{where}: missing {field}")
        if i.get("status") not in STATUSES:
            errors.append(f"{where}: unknown status {i.get('status')!r} (use one of {', '.join(STATUSES)})")
        if i.get("kind") not in KINDS:
            errors.append(f"{where}: unknown kind {i.get('kind')!r} (use one of {', '.join(KINDS)})")
        if i.get("phase") not in phase_keys:
            errors.append(f"{where}: phase {i.get('phase')!r} isn't a heading in phases.md")
        for dep in i.get("depends_on") or []:
            if dep not in item_ids:
                errors.append(f"{where}: depends_on {dep} doesn't exist")
        for dec in i.get("decisions") or []:
            if dec not in decision_ids:
                errors.append(f"{where}: decision {dec} doesn't exist")
        cost = i.get("cost_gbp")
        if cost is not None and not isinstance(cost, (int, float)):
            errors.append(f"{where}: cost_gbp must be a number or null")

    for d in decisions:
        where = d["_file"]
        if not where.startswith(f"{d.get('id')}-"):
            errors.append(f"{where}: id {d.get('id')!r} doesn't match the filename")
        if d.get("status") not in DECISION_STATUSES:
            errors.append(f"{where}: unknown status {d.get('status')!r}")
        sup = d.get("superseded_by")
        if sup and sup not in decision_ids:
            errors.append(f"{where}: superseded_by {sup} doesn't exist")
    return errors


def _cost(value):
    return "" if value is None else f"£{value:g}"


def _link(item):
    return f"[{item['id']}](items/{item['_file']})"


def render_roadmap(items, phases):
    by_id = {i["id"]: i for i in items}
    lines = [HEADER + "# Roadmap", "",
             "What's planned, in progress and done. Each row is a file in `items/`; "
             "what each phase means is in [phases.md](phases.md).", "",
             "Status: " + " · ".join(f"{STATUS_ICONS[s]} {s}" for s in STATUSES), ""]

    active = [i for i in items if i["status"] in ("in-progress", "next")]
    lines += ["## Now and next", ""]
    if active:
        for i in sorted(active, key=lambda i: (STATUSES.index(i["status"]), i["id"])):
            lines.append(f"- {STATUS_ICONS[i['status']]} {_link(i)} {i['title']}")
    else:
        lines.append("_Nothing in progress or queued next._")
    blocked = [i for i in items if i["status"] == "blocked"]
    if blocked:
        lines += ["", "**Blocked:**", ""]
        for i in blocked:
            deps = ", ".join(d for d in i.get("depends_on") or [] if by_id.get(d, {}).get("status") != "done")
            lines.append(f"- {_link(i)} {i['title']}" + (f" — waiting on {deps}" if deps else ""))

    lines += ["", "## By phase", "",
              "| Phase | Done | Total | Est. remaining spend |", "|---|---|---|---|"]
    for key, name in phases:
        phase_items = [i for i in items if i["phase"] == key]
        done = sum(1 for i in phase_items if i["status"] == "done")
        spend = sum(i.get("cost_gbp") or 0 for i in phase_items if i["status"] != "done")
        label = f"{key} · {name}" if key != "ongoing" else name
        lines.append(f"| {label} | {done} | {len(phase_items)} | {_cost(spend) if spend else '—'} |")

    for key, name in phases:
        phase_items = sorted((i for i in items if i["phase"] == key), key=lambda i: i["id"])
        if not phase_items:
            continue
        title = f"Phase {key} · {name}" if key != "ongoing" else name
        lines += ["", f"## {title}", "",
                  "| | Item | Kind | Area | Depends on | Cost |", "|---|---|---|---|---|---|"]
        for i in phase_items:
            deps = ", ".join(i.get("depends_on") or []) or "—"
            lines.append(
                f"| {STATUS_ICONS[i['status']]} | {_link(i)} {i['title']} | {i['kind']} | "
                f"`{i['area']}` | {deps} | {_cost(i.get('cost_gbp')) or '—'} |"
            )
    return "\n".join(lines) + "\n"


def render_decisions(decisions):
    lines = [HEADER + "# Decisions", "",
             "One short record per non-obvious choice: context, decision, alternatives, consequences. "
             "Add a new file rather than rewriting an old one; mark the old one `superseded` with `superseded_by`.", "",
             "| ID | Decision | Status | Date | Area |", "|---|---|---|---|---|"]
    for d in decisions:
        status = d["status"] + (f" by {d['superseded_by']}" if d.get("superseded_by") else "")
        lines.append(f"| [{d['id']}]({d['_file']}) | {d['title']} | {status} | {d['date']} | `{d.get('area', '')}` |")
    return "\n".join(lines) + "\n"


def render_journal(entries):
    lines = [HEADER + "# Journal", "",
             "One file per ISO week (`YYYY-Www.md`): what got built — code *and* physical — what broke, "
             "photos (linked from `anatomy/`), and Henry's ideas. Written during `/weekly-review`.", "",
             "| Week | Summary |", "|---|---|"]
    for e in sorted(entries, key=lambda e: e["_file"], reverse=True):
        lines.append(f"| [{e['week']}]({e['_file']}) | {e.get('summary', '')} |")
    return "\n".join(lines) + "\n"


def render_all():
    """{path: content} for every generated file. Raises ValueError if the sources are invalid."""
    phases = load_phases()
    items = _load(ITEMS_DIR, "R-")
    decisions = _load(DECISIONS_DIR, "D-")
    journal = _load(JOURNAL_DIR, "20")
    errors = validate(items, decisions, phases)
    if errors:
        raise ValueError("\n".join(errors))
    return {
        os.path.join(DOCS, "roadmap", "README.md"): render_roadmap(items, phases),
        os.path.join(DECISIONS_DIR, "README.md"): render_decisions(decisions),
        os.path.join(JOURNAL_DIR, "README.md"): render_journal(journal),
    }


def stale_files():
    out = []
    for path, content in render_all().items():
        current = open(path).read() if os.path.exists(path) else None
        if current != content:
            out.append(path)
    return out


def main(argv):
    try:
        if "--check" in argv:
            stale = stale_files()
            for path in stale:
                print(f"stale: {os.path.relpath(path)} — run python docs/build_index.py")
            return 1 if stale else 0
        for path, content in render_all().items():
            with open(path, "w") as f:
                f.write(content)
            print(f"wrote {os.path.relpath(path)}")
        return 0
    except ValueError as e:
        print(e, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
